image: gradle:5.1.1-jdk8-alpine

variables:
  # Set the location of the dependency cache to a local directory, so that it
  # can be cached between GitLab Continous Integration Jobs.
  GRADLE_USER_HOME: '.gradle'
  GRADLE: 'gradle -Dorg.gradle.jvmargs=-XX:MaxMetaspaceSize=512m'
  SONAR: 'https://sonarqube.ow2.org'

cache:
  paths:
    # Cache the downloaded dependencies and plugins between builds.
    - '$GRADLE_USER_HOME'

build:
  script:
    - $GRADLE build
    - $GRADLE test jacocoTestCoverageVerification
    - $GRADLE uploadArchives
    - '$GRADLE sonarqube -Dsonar.host.url=$SONAR'
